### ISSUE TITLE
travis is not failing correctly

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#114]
When an error occurs, Travis does not fail, but waits for a timeout.

**Comment by ineiti** [comment]
I think, that as long as it's not using `-p=1` this is normal: `go test` starts all tests in parallel, and if one fails, it waits for the others to finish first.

**Comment by ineiti** [comment]
So should we use `-p=1` or ignore this one? It's not as bad as I thought first...

**Comment by ineiti** [comment]
Bump, @nikkolasg ?

**Comment by nikkolasg** [comment]
Is there a way to reproduce the issue ? Because there's no context, no build logs here and so on, so "like that", I'm having trouble to decide on a proper action. Moreover, I don't believe the concurrency is the root of cause here since by default, [golang do not run parallel tests](https://stackoverflow.com/questions/24375966/does-go-test-run-unit-tests-concurrently).

**Comment by ineiti** [comment]
There is parallel _inside_ packages, which is not on by default, and parallel _between_ packages, which is on by default:

https://stackoverflow.com/questions/15721238/serial-execution-of-package-tests

Here it's the second parallelisation I'm talking about. With the other repos we have `-p=1` for avoiding conflicts when the tests run in parallel and all want port `10000` or so.

So the question is: should we add `-p=1` in crypto? When doing _travis-testing_, it would speed things up. But it is not absolutely necessary.

**Comment by nikkolasg** [comment]
Ok so the issue is:
 - when running normally, if one test fails, it does not stop directly but wait the end of all other  tests to finish first. That can takes time (how much ? is it really that bad ?)

The trade off here is either 
- 1) run with `-p=1` so it fails at the first failing test, so we are quick to fail.
- 2) run normally but wait longer when it fails, but it is quicker than 1) when all is fine.

I get the issue now ;) And I have no clear answer for that. As a general guideline, I prefer to fail as quickly as possible but I hate to put a rule that would slow us down in normal cases for that purpose...  I'd would since the time anyway to spin off a travis docker or VM can be quite long enough, it does not change that much to fail rapidly or not. Our crypto tests are supposed to run quite fast normally (and if not, we can open an issue for that ;) ) So I would stick with the parallel execution of packages, but I absolutely don't mind if you prefer to fail rapidly.

**Comment by ineiti** [comment]
`kyber` uses `github.com/dedis/Coding/bin/Makefile` now which defaults to `-p=1`. So no parallel testing anymore.
