### ISSUE TITLE
 [Scalar] UnmarshalFrom should read only exact amount

### ISSUE THREAD

**Issue by nikkolasg** [dedis/kyber#139]
Currently, a `Scalar` is a `nist.Int` and its method `UnmarshalFrom` reads the full content of the given `io.Reader`. It should only read the necessary amount of data, by knowing its expected length since `nist.Int` is always represented using the same length (in practice).

**Comment by jeffallen** [comment]
From reading the code, I don't see the problem. P256's scalar gets UnmarshalFrom from mod.Int, which passes it to marshalling.ScalarUnmarshalFrom, which is careful to read just the bytes it needs.

I wrote this test to prove it:
```go
func TestIssue139(t *testing.T) {
	// 33 bytes worth of zeros
	buf33 := make([]byte, 33)
	// make it into an io.Reader
	buf := bytes.NewBuffer(buf33)
	s := testP256.Scalar()
	s.UnmarshalFrom(buf)

	// Try to read that one last byte, it should still be there.
	var out [16]byte
	n, err := buf.Read(out[:])
	if err != nil {
		t.Error(err)
	}
	if n != 1 {
		t.Error("wrong n", n)
	}
	// now expect an EOF
	n, err = buf.Read(out[:])
	if err != io.EOF {
		t.Error("wrong err", err)
	}
}
```

It passes. I am not checking it in because it doesn't seem to useful to keep around forever (other than in this issue...)
