### ISSUE TITLE
What is clique?

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#158]
Sorry, as there is no PR for v1, I open a lots of issues...

Why do we have the `clique`-subdir? Could we put it somewhere else? One dir with one file inside seems overkill.

**Comment by nikkolasg** [comment]
I know but it's used by the `proof` package and I did not want to mess with unknown code. 
In the meantime, we could probably put it as a sub-directory in proof. WHat do you think ?
Same for `dleq.go`, it must be in its own separate package since its `Suite` requirement are far different from the global package level suite, and it's more a "self contained" system.

**Comment by ineiti** [comment]
Is putting it directly into `proof/clique.go` an option?

For `dleq`: I hesitate to start a mess, putting it directly into `proof/dleq.go` and add a `SuiteDLEQ`-interface.

**Comment by nikkolasg** [comment]
> Is putting it directly into proof/clique.go an option?

+1 for that.

> For dleq: I hesitate to start a mess, putting it directly into proof/dleq.go and add a SuiteDLEQ-interface.

-1 for that... I only see advantages of doing a separate repo for `dleq`:
  + Naming is better. instead of having `proof.DLEQProof`, `proof.DLEQVerifyProof` we can have `dleq.Proof`, `dleq.Verify`. We can simplify namings instead of using the old C way of prefixing everything.
 + Suite definition. See above for the comments about only declaring/using what a package needs as the whole reason we are doing these Suite destructuring.

**Comment by nikkolasg** [comment]
Clique code now in proof subpackage in https://github.com/dedis/kyber/commit/0f4ce8e162c4405fbbd07e55c4776296b5bb809b
