### ISSUE TITLE
util-subdirs

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#163]
Can we put all files in `util/*/*go` directly inot `util`? Most of the directories have only 1 file (no tests) or 2 files (with a test).

**Comment by nikkolasg** [comment]
Please no. I'd prefer keeping the packages separated because they really are doing different completely different things. I really don't think it's a problem to have a package with two files inside which provide a complete API for a specific task. 
See https://blog.golang.org/organizing-go-code
That being said, there can be one package we put directly under the `util` namespace  AND there may be some package that we leave in the top root folder. I've moved `random` into util but maybe it should stay at the top.

**Comment by ineiti** [comment]
The given link just says `Look to the Go standard libraries as a guide. Some of its packages are large and some are small.`...
If you think these subdirectories make sense, keep it.

**Comment by nikkolasg** [comment]
The question is does it make more sense to put in one package ? What are the advantages ? 
I would have even prefered to rename `util` to `lib` so it's clear that there will be different functionalities / system inside, instead of `util` which suppose "one size fits all" kind of solutions... But crypto is already a lib itself...

We can try like this and if we see it's producing too much boilerplate code then trying out everything under the `util` folder. ?

**Comment by ineiti** [comment]
`like this` == what? subdirectories or all in one directory?

**Comment by nikkolasg** [comment]
I meant subdirectories first. If we see it's troublesome during the porting to onet/cothority, then we can still put back everything in the `util/` folder. Is that ok ?
Otherwise, if you feel *some* packages could be merged, please say so, I'm willing to reduce the number of packages, but not so to make a "mashup" ;)

**Comment by nikkolasg** [comment]
For example, there is `encoding` and `marshalling` unfortunately, due to the current structure of the crypto code, it's not really easy to merge both because we can't test it. I had circular imports issues while trying to at least.

**Comment by ineiti** [comment]
Leave as is for the moment.
