### ISSUE TITLE
proof/dleq

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#165]
I'd also put the files in `proof/dleq` to `proof`, because there are only two, and other proofs are directly in the `proof`-directory, too.

Or is there a special reason only these files are in a subdirectory?

**Comment by nikkolasg** [comment]
1) `dleq` requires a much more simpler `Suite` than the rest of the `proof` package, so since we're doing that suite optimization, we should go for having the `dleq` package taking only what it needs. This is what we discussed that we needed to exactly formulate the requirement of each packages so each one could only declare what functionalities they need to use. So you could see that as one side effect (having more packages).
2) Again, it's a small self contained suite of methods. In the same spirit of `sign` we have `sign/cosi` `sign/anon` etc.  I believe `proof` itself can be splitted into different packages (there seems to be a `hash proof` and the `general proof framework of Camenish/Stadler` but since I don't know much I did not want to touch.

What do you think ?
