### ISSUE TITLE
cipher.go

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#202]
Looking through the top-level files, I have some questions regarding `cipher.go`:

1. why is the `Cipher`-struct in `/`? 
2. do we need `NoKey` and `RandomKey` in `cipher.go`?

My main complaint is that it's a top-level file and as such should be as minimal as possible. For the moment the godoc looks strange with only the `Cipher`-struct showing all its methods, while all other interfaces (which are more important) are shown 'blank':

http://godoc.org/gopkg.in/dedis/kyber.v1

**Comment by nikkolasg** [comment]
1. Because our old `Suite` definition must returns a `kyber.Cipher`. We could move `kyber.Cipher` to `cipher.Cipher` but 1) I find the naming duplication not very elegant, 2) I still prefer having all our abstractions, interfaces at the top root level, or at least in the same package name, like we had before in `abstract/`.
2. I guess it would be fine and best if we move both to `cipher/` package as it does not seem they are used in the top level package, yes. Well spotted !

**Comment by nikkolasg** [comment]
Regarding your global comments... Well. It does not bother me too much tbh. I don't think it will have a huge impact on the usability of the repository... But maybe I'm wrong ;)

**Comment by ineiti** [comment]
So move `NoKey` and `RandomKey` to `cipher/`, then this is closed.
