### ISSUE TITLE
PrimeOrder

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#203]
@bford wrote
The Group.PrimeOrder() method still needs to be either eliminated or renamed to something less confusing.  (It sounds like it's asking whether the group is prime-order, but what it returns is actually whether the order of the Base() point is prime-order.)  What all still depends on this?  More generally, we need to systematize the API for obtaining basic properties of the group in question - e.g., its order, whether there's a cofactor, etc.  Perhaps with several methods, perhaps with just one method that returns a GroupProperties struct of some kind, not sure.

From @nikkolasg to @bford 
1. I would advise for a `GroupProperty` struct  but given that we only have a few numbers of parameters to put (order of the group and cofactor ?), it's also OK for me to add those functions to the `Group` interface directly. What do you think ? 
2. Regarding the amgiguity you mentionned, I'm not sure about the best approach. Maybe a `PrimeCurveOrder` and `PrimeGroupOrder` ? In case of ed25519, the former returns false and the latter true.

**Comment by ineiti** [comment]
Or we add a general key/value storage to each group - but I'm not sure this would really be useful. Do we have a use-case where we depend on any of this information? Or would it be enough to simply document those parameters, so that when it is used, it is at least known in the documentation?

**Comment by nikkolasg** [comment]
Good point. We actually don't have any use-case where we depend on any information of the like dynamically. Even for groups that supports hiding (Elligator mapping and the likes), I guess it's relatively fine to document that clearly.
So I'm fine with having these properties in the documentation then.

**Comment by ineiti** [comment]
Discussing with @bford: remove `PrimeOrder`. If something in unstable needs it, add an interface for the unstable branch.

**Comment by nikkolasg** [comment]
All right.

**Comment by bford** [comment]
As I mentioned to Linus, the only place I remember PrimeOrder being needed is within the generic Group testing code, which calls that in order to decide whether to run Group tests that depend on the the base point being a prime-order base point.  In particular, the Inv (inversion) test for example depends on the base point being prime-order, and won't work otherwise.

But I'm not sure if we actually still use the non-prime-order base points anywhere, so this may well be moot.  If it isn't - if that test is still needed - then the PrimeOrder method can still be kept, but the test code can simply have a small, specialized interface containing only that method, and do a cast to that interface to get it.  We might change this to something better down the road, but it's not worth cluttering the main interfaces or holding things up because of this.

**Comment by nikkolasg** [comment]
Right. So plan is:
- remove `PrimeOrder` from the interface definition
- check if test still needs this for our suites
    -> if yes, create a small wrapper interface that defines `PrimeOrder`
    -> if no, then nothing to be done !
