### ISSUE TITLE
Replace Cipher with Xof

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#206]
From @nikkolasg:
Apparently, @bford wants the `cipher` package to be out of v1. That means we must get rid of the `sign/anon` package as well in v1 too. That is ok for me. BUT our `pop` service needs the `sign/anon`, and IIRC we wanted `pop` to be included in cothority.v2. In short, the problem is that we want to have a stable `pop` service which depends on the unstable `sign/anon`. We could try some casting magic between `github.com/dedis/kyber` and `gopkg.in/dedis/kyber.v1` but I strongly advise against that as it's "one more trick" that only us, engineers, will understand. In my opinion, I see two solutions: 
    + We keep `cipher` and `sign/anon` in v1, so we can keep the `pop` service in cothority.v2
    + We plan to not include the `pop` service in cothority.v2. 

I'm more in favor of the former option...

**Comment by ineiti** [comment]
+1 for keeping cipher and having sign/anon in v1.

**Comment by ineiti** [comment]
Discussing with @bford, `cipher` is not stable as it's only used by a few things. It's a useful experiment, but not stable.

So, pop will not be stable unless `cipher` is stable. No `cipher` in `kyber.v1`.

**Comment by nikkolasg** [comment]
I also need `cipher` for `vss` and `dkg`.....
Seriously, we need that. Why is `cipher` not stable ? What's wrong?

**Comment by nikkolasg** [comment]
And anyway, we need the `cipher.Stream` interface for `Pick` . How would we do without it ? Just remove `Pick`?? I don't see it feasable.

**Comment by bford** [comment]
Can you point out the specific modules or source files that depend on cipher from vss and dkg?  How are they using the Cipher functionality - just as a glorified hash function or more significantly?

And cipher.Stream is from the Go standard cipher package, not Kyber's.  (That's a bad source of confusion due to naming, I know.)

The intent was to keep Cipher out of stable in part because it implements a just-slightly-exotic general-purpose symmetric cipher abstraction representing a "general sponge function" that's probably reasonable but hasn't yet undergone careful cryptographic review (maybe @daeinar could help with that :) ) and I seem to recall there were a few niggly unresolved issues with it (such as issues with starting state, e.g., producing a bunch of all zeros as output if used uninitialized).  If we need to make it stable then I'm sure we can, but that'll be more work and attention before we can really call Kyber v1 ready.

**Comment by bford** [comment]
Actually, come to think of it, that recent paper from the Keccak team with the interesting new parallelizable construction might be a good candidate for a better, more principled and formally analyzed foundation for the functionality the Cipher abstraction was intended to provide.  I think this was Farfalle/Kravatte: https://keccak.team/kravatte.html

But I don't think we should really hold up Kyber v1 for that.

**Comment by nikkolasg** [comment]
Agreed with that, and my worry was due to that confusion with the golang package, I'm Ok with that. Indeed vss uses it as a "glorified hash function" so I'll need to code stg that returns a `golang-cipher.Stream` from a slice of bytes but that's fine.  
The thing I have huge strong feelings against is the future plan of action linus sent to us you discussed but maybe that's mostly because I don't get it...

**Comment by bford** [comment]
Yeah, sorry you couldn't be at the impromptu meeting Linus and I had...  Linus can catch you up on what we discussed; see what makes sense and what doesn't, go ahead and work on the part that makes sense, and we can keep hashing out the parts that don't as quickly as we con. :)

**Comment by Daeinar** [comment]
@bford Yeah kravatte is nice and in fact uses the masking scheme from our [Eurocrypt 2016 paper](https://eprint.iacr.org/2015/999) to make it really efficient. ;) It might be indeed worth thinking about using that construction instead of a regular sponge. I also agree that we should not push back Kyber v1 for that though. Happy to help reviewing the underlying cryptographic constructions at some point.

**Comment by nikkolasg** [comment]
After having discussed again with linus and philipp, I think it all depends on the goal we want to achieve. I think it would be perfectly fine to assume we just want a stable version for students to work and therefore keeping `cipher` would also be reasonable. In the meantime, reviewing that package is something that has to be done definitely.

**Comment by jeffallen** [comment]
As an experiment I did "rm -rf cipher; go test -tags vartime ./..."

I found that group/curve25519/suite.go depends on golang.org/x/crypto/sha3.NewShakeCipher128.
Likewise nist/suite.go and nist/qrsuite.go.

I commented out those references in order to proceed, and then I found that lots and lots of test code depends on running the Cipher(in []byte) function from the current suite in order to create a seeded PRNG (with a known seed, to make tests deterministic).

**Comment by jeffallen** [comment]
We have decided to try to replace kyber.Ciper with a new abstraction of the concept of an extensible output function (XOF).

The current work is to make the new Xof type, and create two implementations of it with keccak and norx sponges behind it, and then use it in sign/anon to confirm that it can replace kyber.Cipher.

**Comment by jeffallen** [comment]
Done in #246
