### ISSUE TITLE
Add a schnorr-interface and use this for `eddsa` and `cosi`

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#218]
Proposition from @bford for `sign/schnorr` - I filled in the interfaces - if you think it needs to be changed, feel free to edit this message:

```go
type Suite interface {
  Group

  SchnorrKey(s cipher.Stream) Key
}

type Key interface{
  Commit(s cipher.Stream) (abstract.Scalar, abstract.Point)
  Challenge(commitment, message []byte) (abstract.Scalar, error)
  Sign(commitment abstract.Point, response abstract.Scalar, mask *Mask) ([]byte, error)
  Verify(message, sig []byte) error
}
```

This should be implemented by `sign/eddsa` and given as an argument to `sign/cosi` methods from `cosi-api`-branch.

**Comment by bford** [comment]
NewKey -> SchnorrKey, because Go interface method names are effectively in one global namespace (unlike normal names), and we might want different but compatible Suite interface extensions to create different types of keys (e.g., encryption keys, DH keys, ...)

And on further thought, the Private and Public interfaces should probably just be merged into one type Key (i.e., schnorr.Key), which can dynamically represent either a public or a private key.  (just like there's just one Point interface type that can represent many different things.)  The Sign method won't work right (e.g., might just panic) if invoked on a schnorr.Key instance that contains only a public key.

The Commit method should be part of schnorr.Key, not Suite.  The schnorr.Suite interface should contain only the one SchnorrKey constructor method.

The main idea is for this interface to embody all the functionality specific to a particular bitstream encoding of Schnorr signatures (e.g., EdDsa25519 and EdDsa448), which higher-level signing logic can then use to implement fancy Schnorr-based signing schemes.  In particular, sign/cosi would build on top of this interface, as well as perhaps sign/anon, and the Shamir threshold signing code.  

Our standard/stable implementation(s) of the SchnorrKey interface will implement the EdDSA25519 and perhaps soon EdDSA448 schemes bitstream-compatible with the RFC spec, including the way new private keys are generated, and the way commits are generated using SHA512 (for EdDSA25519) or SHAKE-256 (for EdDSA448).

But it should perhaps be feasible to create alternative implementations of this interface not only for different curves, but also to produce (c,r)-representation rather than (R,S)-representation Schnorr signatures.

The specific methods proposed above might not be quite enough (or might not have quite enough of or quite the right arguments), but that's the gist of what I had in mind.

**Comment by ineiti** [comment]
1. Updated my code to reflect your comments
2. What do you mean by _Go interface method names are effectively in one global namespace_? I did this playground-example: https://play.golang.org/p/Q_RHS2PlNu - it looks like we can have different definitions of `NewKey` in different interfaces - or did I misunderstand you?

**Comment by nikkolasg** [comment]
I think he means that if one day we want to implement another private / public key generation for a different purpose than signing, we won't be able to use `NewKey` since that's already taken.
```
type Private interface {
    NewSchnorrKey()
    NewDHKey()
    ...
}
```
But to me that does not make much sense to bind these other methods to a `Private` which implements a `Group`: a DH key or encryption key will probably not have anything related to the `Group`.

**Comment by bford** [comment]
Exactly: if there is both a SchnorrSuite interface and a DHSuite interface, both of these interfaces require methods called NewKey (but with different semantics and likely different arguments), then it will be impossible to create a single concrete suite object that implements both the SchnorrSuite and DHSuite interfaces.  Thus, the NewKey method names are effectively part of a single global interface-method-name namespace, because things start going south as soon as method names defined by completely different and independent interfaces in different and independent models start encountering name conflicts.

This is one of Go's language flaws, which I'm sure I'm not the first to recognize.  Maybe they'll fix this flaw one day, e.g., by providing a way to disambiguate somehow between "DHSuite.NewKey" and "SchnorrSuite.NewKey" in a Suite object that wants to implement both separately.  But that's not something I expect to get fixed soon.  So for now we have to keep these interface method names reasonably unique, unlike most other identifiers in Go.

**Comment by nikkolasg** [comment]
Giving it some further thoughts, I have to say I don't really appreciate the benefit here.
- Regarding the new interfaces, it seems that they are specifically designed to work with CoSi (separation of `Commit` , `Challenge` and `Sign` is only needed in CoSi. In this respect, I'm asking: "why do we need interfaces at all" then, it should be fine to define those methods only for CoSi and we're done. I would rather much prefer a more generic signing framework as the one Bryan [tried some ago](https://github.com/dedis/kyber/pull/46/files#diff-68d6eb30274fb35e4ae3c53d747644a1R36). This do not assume anything about the concrete signing scheme.
- Regarding the problem that it is supposed to solve: namely, how to create correct ed25519 private keys used for signing, it seems for me that only the first interface is useful, namely the 
```go
type Suite interface {
  Group

  SchnorrKey(s cipher.Stream) kyber.Scalar
}
```
If it is placed in the `sign/schnorr` package, then users that need to sign something using schnorr have to make sure they are using a `Suite` that is able to produce correct private key for that.
Again, I would much prefer the more general signing framework of Bryan, because I believe that would allow us to hide that detail from the user.

**Comment by jeffallen** [comment]
There is not a clear enough plan here yet to have this in v1, so @ineiti and I removed it.

**Comment by bford** [comment]
Removed it from v1 or removed it entirely?  We need to have a standard tagging/labeling scheme for issues like this that may be worth discussing further for down the road, e.g., v2+.

**Comment by jeffallen** [comment]
We are working like this: Things in the kyber v1 "epic" are absolutely must haves. Things that got discussed and there is not a compelling next step get closed. Things that are for the future but are not solid enough to be in kyber v1 stay open, like this issue. I've put the "enhancement" tag on this to show that it is still wanted, but is not for right now.

**Comment by bford** [comment]
Sounds good, thanks for clarifying.

**Comment by nikkolasg** [comment]
> Things that are for the future but are not solid enough to be in kyber v1 stay open, like this issue. 

... ?
