### ISSUE TITLE
kyber/group/mod/sqrt.go

### ISSUE THREAD

**Issue by jeffallen** [dedis/kyber#231]
This implementation can probably be replaced with the one that is now in Go math/big:

https://godoc.org/math/big#Int.ModSqrt

**Comment by bford** [comment]
Yes, but in situations like this where a version has appeared in the standard Go library or whatnot, please be careful to:

(a) make sure the one in the standard library is really "as good or better than" the one we had - e.g., I think in a few cases the standard big.Int versions of something had restrictions or assumptions that weren't good for our crypto use-cases, although I don't recall this being an issue in the case of ModSqrt in particular;

(b) make sure that the version in the Go standard library didn't just appear in the very very latest version of Go released two days ago, but preferably was released at least two or three Go minor versions ago, to avoid unexpectedly restricting our Kyber library to use with only the most bleeding-edge latest version of Go.

Otherwise, no objections to such elimination of now-redundant functionality. ;)
