### ISSUE TITLE
Remove SetVarTime from interface Point (but still support the concept for callers who opt-in)

### ISSUE THREAD

**Issue by jeffallen** [dedis/kyber#250]
First principles:
1. smaller interfaces are better
2. YAGNI (you aren't gonna need it)

So the goal here is to make it possible to do this, but not have it be in every implementation of kyber.Point.

(this comment was edited based on Bryan's feedback in comment 2 and 3)

**Comment by bford** [comment]
Wait, what?  The intent of the SetVarTime call was to allow clients to give the curve implementation the permission to use vartime optimizations *dynamically*, e.g., when using Scalars and Points for "public operations" like just verifying a digital signature (as opposed to signing).  The Ed25519 already has a vartime scalar multiply path that's significantly faster when it's allowed to be constant time; the intended purpose of SetVarTime was to make it so that and similar vartime-optimized code paths can be used for appropriate purposes.  That doesn't seem like something that a compile tag can deal with.

**Comment by bford** [comment]
Perhaps SetVarTime was named confusingly; perhaps it should have been colled AllowVartime or something like that?

**Comment by jeffallen** [comment]
I understand better the point of this now (before I was reading the implementations of it, not the declaration in kyber/group.go).

The only place in the entire kyber source where this is possible right now is in group/edwards25519/point.go on type kyber.Point. There, the "allow varTime" policy is implemented on a per-point basis, not on a per-suite basis as I previously understood.

SetVarTime is not currently used in kyber, onet, or cothority.

So I propose that we make "type VarTimePossible interface { AllowVarTime(bool) }". Then callers who want to allow variable time operations on a given kyber.Point will be able to find out if it is possible and do it.

**Comment by nikkolasg** [comment]
I think I prefer your solution @jeffallen , as it will very soon forces us to think how to manage properly all these "features" that a `Point` or `Scalar` can offer. So far it's more on a adhoc basis, checking for individual property by casting, but maybe another way is possible !

>  and callers will not need the vartime tag in their source to correctly take advantage of this.
+1 for this. After introducing this flag, I realized it's not super usable, and my IDE is not happy about it too .^^
