### ISSUE TITLE
Consider adding property-based testing

### ISSUE THREAD

**Issue by kc1212** [dedis/kyber#312]
A lot of our tests are performed using just a couple of fixed, arbitrary messages. But encryption and signature schemes can be seen as pure function, which is exceptionally suitable for property-based testing. In brief, property-based testing, i.e. quickcheck, will test for one or more properties that the programmer specifies, for example `Dec(Enc(m)) == m`, with random inputs, up to a user defined size/length. Consider improving our tests using the quickcheck package https://golang.org/pkg/testing/quick/

**Comment by nikkolasg** [comment]
While this sounds generally reasonable, I'm actually worried about "randomized testing" for cryptographic schemes for multiple reasons:. 
+ Relying on randomized / fuzzing testing to assert that our construction is "good" is misleading and may let us believe that "if it passes this fuzzing test, it must be secure", while it's not true *at all*. Verifying with random inputs does not bring more guarantees to our cryptographic constructions, because we will never know if it is valid for all inputs anyway.

+ It might happen that we have sometimes a test failing for some input and it might be quite hard to debug if multiple developers can't get the same test base easily,i.e. can't reproduce a minimum test which fails.

Again, while in general I think it's a good idea to try out (in onet!), I'm not so sure about this in the context of kyber, but I'd be happy to hear any other thoughts on the matter !

**Comment by kc1212** [comment]
Let me address your points:
- Property-based testing is not to assert that a cryptographic construction is secure, it's more to do with correctness. It's simply to catch corner cases caused by a developer bug. For example, an empty message.
- This is not what a good quickcheck implementation will do. I don't know about go's implementation but the Haskell and Rust implementations do the following. They start by trying random inputs (it's not exactly random but it tries inputs with different properties, e.g. messages of different lengths, u can also specify how you want to generate these random inputs). Upon hitting an input that causes the test to fail, it will try to reduce the input and try to reproduce the same failure such that the bad-input is of minimum size/length. Every step of the reduction is printed out, this is very useful for debugging because you can see what kind of inputs are causing failures. Finally the developer can use the smallest bad-input (or any other one in the reduction chain) to reproduce the error.

**Comment by nikkolasg** [comment]
> Property-based testing is not to assert that a cryptographic construction is secure, it's more to do with correctness. It's simply to catch corner cases caused by a developer bug. For example, an empty message.

I'm not educated enough in property-based testing and even less in the quick package that Go has so bear with me please :) :  

+ What kind of corner cases are you envisionning ? Here's a few I can think of:
   - empty messages: this should already be handled correctly for most of our schemes, since there is always some notion of indistinguishability
  - nil point / scalar: this should just panic
  - ... ?

+ How would the `quick` package help in a better way that just addressing those corner cases *systematically* in the testing ? With the current PR reviewing process we have here, we have always at least another pair of eyes on every code that gets shipped. It's probable that we miss some corner cases, but I fail to see, in the kyber context, how the quick package will help catch those ? (wrt. to the first question)

**Comment by ineiti** [comment]
For a 1st shot, get a simple package up and testing using `testing/quick`. Something like `Schnorr.Verify`.

**Comment by kc1212** [comment]
Closed via #334
