### ISSUE TITLE
Function of call to UnsafeSetResponseDKG in rabin/dkg.go/DistKeyGenerator.ProcessDeal

### ISSUE THREAD

**Issue by coventry** [dedis/kyber#373]
What's the role of [this call](https://github.com/dedis/kyber/blob/89ca875/share/dkg/rabin/dkg.go#L291) to [`UnsafeSetResponseDKG`](https://github.com/dedis/kyber/blob/89ca875/share/vss/rabin/vss.go#L679)?

```golang
	d.verifiers[dd.Index] = ver
	resp, err := ver.ProcessEncryptedDeal(dd.Deal)
	if err != nil {
		return nil, err
	}

	// Set StatusApproval for the verifier that represents the participant
	// that distibuted the Deal
	d.verifiers[dd.Index].UnsafeSetResponseDKG(dd.Index, true)
```
It seems like calling it with `true` would override any complaints made during the call to `ProcessEncryptedDeal` a few lines earler, which might lead to [`DealCertified`](https://github.com/dedis/kyber/blob/89ca875/share/vss/rabin/vss.go#L658) inaccurately returning `true`  or [`SecretCommits`](https://github.com/dedis/kyber/blob/89ca875/share/vss/rabin/vss.go#L279) being triggered when there aren't actually enough approvals but [`EnoughApprovals`](https://github.com/dedis/kyber/blob/89ca875/share/vss/rabin/vss.go#L646) is returning the wrong value.

**Comment by nikkolasg** [comment]
This call is done to "simulate" the fact that the dealer, which is also a verifier,  broadcasts its response to its own deal, which we assume will be true (what would be the point of making a complaint of its own deal, bc it means you have to reveal your deal, which you could have done anyway). In order to not have to send a response to our own deal, we just set it as true directly. It saves one message per deal...
It does *not* override the verifier's response I believe. There are two cases:
1. the verifier and the dealer are the same, so we assume the dealer assumes its deal is correct so we override "true" with "true".
2. The verifier has index i and dealer index j. In the verifier's response map, there will be the response of the verifier at the index j (the "resp" variable), and the *simulated* response of the dealer at the index j (which we consider it being always true).

Additional comment: Back at the time, we coded first the verifiable secret sharing scheme, then the dkg scheme in a separate package. Looking back at this decision, I think it was a mistake since the DKG scheme is very tightly coupled with the VSS scheme used, and it's more than simply "DKG is *n* VSS in parallel".  For example. this "UnsafeSetResponseDKG" also is useful to set responses to complaints when the timeout occurs.

**Comment by coventry** [comment]
Thanks for clarifying, @nikkolasg, that makes sense. Is a `dkg DistKeyGenerator` supposed to run its own `Response`s from `dkg.ProcessDeal` calls through `dkg.ProcessResponse`, so that it can register any complaints about other's deals on `dkg.verifiers[dkg.index]`? Is the exclusion of those responses [in `dss_test.go/genDistSecret`](https://github.com/dedis/kyber/blob/master/sign/dss/dss_test.go#L178) just to speed things up a bit? (The test does run fine with that exclusion removed. Also, it's just a test, so not that critical.)

**Comment by coventry** [comment]
Thanks for clarifying, @nikkolasg, that makes sense. I'm not clear yet on where the DKG is registering its own approvals/complaints about other's deals, but I can probably track it down.
