### ISSUE TITLE
[cosi] Deterministic signature without random participant commitment

### ISSUE THREAD

**Issue by cedricfung** [dedis/kyber#388]
The draft and code both generate random participant commitment, is it safer or better to generate each participant commitment like regular EdDSA?

```
 r = H ( H b , … , 2 b − 1 ( k ) , M )
```

k is the participant private key and M is the message.

**Comment by cedricfung** [comment]
If the participant commitment is deterministic, and the public keys are fixed and in deterministic order, the mask will be deterministic for the same participants. Then the signature will be deterministic.

**Comment by bford** [comment]
It's not possible or safe to make signatures deterministic, in the way normal EdDSA does, in a collective/aggregate signing protocol like CoSi.  So definitely don't do that!

To ensure the deterministic signing scheme is secure,  the private random value used to seed all the signer-internal randomness *must* depend on *everything* that the eventual signature will depend on.  For non-collective signatures, that's just the message M, so no problem.  But for collective signatures, the eventual signature will and must depend on not just the message M but also on all the other signers whose signatures are to be aggregated.  Single-signer EdDSA uses its private deterministic randomness to produce the commit, which must always be unique (one-time-use) for a given signature otherwise Schnorr's security falls apart immediately.  But the collective signature we eventually produce in CoSi must depend on stuff from other cosigners (e.g., the collective challenge, which *must* depend on *all* nodes' commitments for security), and there's no way a given signer can predict that other stuff at commitment time.  So if a cosigner used an internal deterministic seed like EdDSA to produce its commits, there's no way it could make that seed depend on everything it needs to depend on to be unique and secure, and it will end up being vulnerable to commit-reuse attacks, which will completely break the signing scheme's security and make the signer's private key recoverable by anyone with a bit of arithmetic.

So again, definitely don't use deterministic private randomness in a two-phase collective signing scheme like CoSi!

Hope this helps. :)

**Comment by cedricfung** [comment]
@bford Thanks for the explanation. We have already figured out that this is vulnerable. What if we change the signature to non-EdDSA? e.g. `s = H(H(R,A,M)) r + H(R,A,M)a`, is this more secure than the random EdDSA?
