### ISSUE TITLE
[dss] Rekeying & Rotating Vault

### ISSUE THREAD

**Issue by HAOYUatHZ** [dedis/kyber#397]
does https://github.com/dedis/kyber/tree/master/sign/dss
support rekeying / rotating keys?

can I have key shares changed without changing  longterm commiments (the final publickey)?

**Comment by jeffallen** [comment]
The `dkg` package has the ability to reshare a key across different share holders. See the Config structure: https://github.com/dedis/kyber/blob/aa4f64554da8db8bc16927f34b075c330ed8ad1e/share/dkg/pedersen/dkg.go#L26

Because package `dss` can use a key generated in a decentralised manner via package `share/dkg/pedersen` for example, it should be able to support reshaping keys.

I have to admit, though, that since we added resharing to DKG, we have not come back to try using it in the context of DSS. Perhaps @nikkolasg knows more.

Please re-open this issue if you try it and it doesn't work as expected.
