### ISSUE TITLE
Modulo bias

### ISSUE THREAD

**Issue by cgrigis** [dedis/kyber#439]
_Security Code Review finding:_

Another modulo bias in `kyber` was found in [`pairing/bn256/point.go` on line 239](https://github.com/dedis/kyber/blob/9ac80102d756a21f318685e230e33791c44b5e2e/pairing/bn256/point.go#L239), notice this is not necessarily a danger depending how the `hashToPoint()` method is later used, but it could be done using iterative hashing and masking until a value below the modulus is found to ensure a uniform distribution of the `x` coordinate.

**Comment by pierluca** [comment]
@K1li4nL I see the PR fixing this was closed, because it introduced non-backwards-compatible changes, but what's the status on this ?

**Comment by K1li4nL** [comment]
I see a couple possibilities: 
1) Given #443,  we get rid of BN256 altogether since we now have BLS12-381 in master and close this issue
2) If we want to keep BN256, update the documentation to make sure this is not lost and close this issue. 
3) Break backward compatibility, I don't think this makes much sense since this curve is not recommended and ultimately unfix-able, mentions it out of completeness.

**Comment by pierluca** [comment]
Okay, let's go with option 2 then !

**Comment by K1li4nL** [comment]
Will update pr #538 to add that then
