### ISSUE TITLE
Inconsistent edwards25519's Scalar (un)marshaling for some inputs.

### ISSUE THREAD

**Issue by pszal** [dedis/kyber#488]
The minimum working example below outputs `false` for me, which I believe is incorrect (`v3.1.0` on Apple M1 Pro).
```
package main

import (
	"fmt"

	"go.dedis.ch/kyber/v3/group/edwards25519"
)

func main() {
	g := edwards25519.NewBlakeSHA256Ed25519()
	s1 := g.Scalar()
	if err := s1.UnmarshalBinary([]byte("00000000000000000000000000000000")); err != nil {
		panic(err)
	}
	b, err := s1.MarshalBinary()
	if err != nil {
		panic(err)
	}
	s2 := g.Scalar()
	if err := s2.UnmarshalBinary(b); err != nil {
		panic(err)
	}
	fmt.Println(s1.Equal(s2))
}
```

**Comment by ineiti** [comment]
This is on purpose:

When you create a `[]byte("0")`, the hexadecimal representation is `0x30`, and not `0x00` as you might have supposed. This is because go converts the `string` `0` to its byte representation.

So what you're asking is to create a scalar full of `0x30` bytes. In the next step, you call `MarshalBinary` which reduces this number by calculating the modulo with the field-size, `2^255 - 19`. As a buffer full of `0x30` is greater than `2^255-19`, it is reduced and does not hold all `0x30`s anymore.

You can do

```
s1.Zero()
```

Instead of `UnmarshalBinary` with an all-zero `string`, or

```
UnmarshalBinary([]byte(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0))
```

And it will work as supposed.

**Comment by pszal** [comment]
My point is that I found it a bit confusing that such created scalars are **not** equal. 
btw.  I believe that "0" is represented as 0x48

**Comment by ineiti** [comment]
> My point is that I found it a bit confusing that such created scalars are **not** equal.

From the documentation: _ As should be obvious, this library is intended to be used by developers who are at least moderately knowledgeable about cryptography_

And the ASCII representation of "0" is 48 decimal, or 30 hexadecimal, which is represented in many programming languages as 0x30. 0x48 hexadecimal is 72 decimal, which is "H"... Why do people not know their ASCII tables anymore :)

If you are confused by this, please choose another library. Libnacl is a good one, Tink from Google probably also, but I have no experience with the latter.

**Comment by pszal** [comment]
Thanks for the clarifications and suggestions! Oh yes, 0x30 ;-).
